### ISSUE TITLE
Use z3 with statically-linked glibc in deployment

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#104]

**Comment by Heizmann** [comment]
@greitsch I think I need your help here. I would like to let your Gentoo Ebuild create a static version of Z3. (We use the binary from Monteverdi for the release - right?)
As a first step, the ebuild runs
    ``python scripts/mk_make.py --prefix="${D}opt/z3"``
this creates the
    ``build/config.mk``
file.
In order to get the statically linked binary, we have to add ``-static`` to ``LINK_FLAGS`` in this file. By default ``LINK_FLAGS`` is empty, maybe we can just replace the line ``LINK_FLAGS=`` by the line ``LINK_FLAGS=-static``

**Comment by Heizmann** [comment]
Deluxe version of this: having a ``-static`` use flag in the Ebuild.

**Comment by greitsch** [comment]
I can try this out. This working depends on whether or not Z3 supports static library compilation. I'll fiddle around with the ebuild a bit and will come back to you in about 30 min with this.

**Comment by Heizmann** [comment]
It works if I add the ``-static`` manually. I had to do this for the Termination Competition where Ultimate is running on StarExec.

**Comment by greitsch** [comment]
Not sure if ``LINK_FLAGS`` is the correct system variable, though. Maybe one should rather use ``LD_FLAGS`` or ``CFLAGS``? Where did you get the ``LINK_FLAGS`` info from?

**Comment by greitsch** [comment]
Plus: Maybe it's sufficient to use ``-static-libgcc`` instead of ``-static``? In the case of GCC this should just link to GLIBC statically, but use the dynamic versions of all other libraries. What do you think?

**Comment by greitsch** [comment]
The Z3 ``mk_make.py`` script provides the switches ``--staticbin`` and ``--staticlib``.

[Here](https://github.com/ultimate-pa/ultimate/files/729917/z3-ebuild.zip) is an updated ebuild for Gentoo-like systems that supports two new use flags:
``static      : !!do not set this during bootstrap!! Causes binaries to be statically linked instead of dynamically``
``static-libs : Build static versions of dynamic libraries as well``

You can either add ``sci-mathematics/z3 static`` (and/or ``static-libs``) to your ``/etc/portage/package.use`` or compile Z3 once with

``$ USE="static" emerge --oneshot z3``

(Note that the latter command will only compile Z3 statically until you do an ``emerge @world`` which will cause the default Z3 version with all use flags set in ``/etc/portage`` to build again and ignore the "static" one.)

I tested the ebuild only briefly. On the first glance, the compilation seems to work as intended; the static library is compiled with the second use flag. Could someone please try whether Ultimate runs using a Z3 version compiled with the ``static`` use flag?

----

How to use the ebuild:
You need to create a local portage repository following [the description in the Gentoo Wiki](https://wiki.gentoo.org/wiki/Handbook:AMD64/Portage/CustomTree#Defining_a_custom_repository).

Suppose you've added the local portage repository ``/usr/local/portage``, you'll need to unzip the ``z3-ebuild.zip`` to ``/usr/local/portage/``. This will create the ``/usr/local/portage/sci-mathematics/z3/`` directory and Z3 ebuild. If compilation fails due to manifest errors, you'll need to call ``ebuild z3-9999.ebuild clean digest`` in ``/usr/local/portage/sci-mathematics/z3/``.

After that you should be able to use ``emerge z3`` to compile Z3 and automatically install it on the system to ``/usr/bin/z3``.

**Comment by greitsch** [comment]
@Heizmann I've also updated the ebuild on Monteverdi. I didn't change any use flag yet, though.

**Comment by danieldietsch** [comment]
I can test our deployment with all the binaries. I would build a current z3 version with both, `--staticbin` and `--staticlib`, correct?

**Comment by Heizmann** [comment]
``--staticbin`` is sufficient
We do not need ``--staticbin`` and it might increase the size.

**Comment by danieldietsch** [comment]
You mean we dont need '--staticlib' right?

**Comment by greitsch** [comment]
@danieldietsch Correct. You only need the static-lib flag, if you wanted to use Z3 as a library instead of doing a system call to the executable. Therefore, it should be sufficient to only use ``--staticbin`` (or the corresponding use flag on monteverdi).

**Comment by danieldietsch** [comment]
I ran deployment tests against both variants of z3 with version master 7386e2f3e942b025d8266323dc299055a7dd1efa. Good news, both versions behave the same. Bad news, this version seems to have multiple crashes on examples that ran fine with our last version (unfortunately, I dont know which version this was). 

An example for such a crash is the following: 
<code>java -Xmx12G -Xms1G -jar plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -data @user.home/.ultimate -tc /storage/ultimate/releaseScripts/svcomp2017/UAutomizer-linux/AutomizerMemDerefMemtrack.xml -i
../../../trunk/examples/svcomp/array-memsafety/array02-alloca_true-valid-memsafety.i -s /storage/ultimate/releaseScripts/svcomp2017/UAutomizer-linux/svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf --witnessprinter.graph.data.producer Automizer --witnessprinter.graph.data.architecture 32bit --witnessprinter.graph.data.programhash f42aa215a16d5e0efb670a585ba0238849a32fc4
</code>

I wont open a separate ticket because it may just be bad luck, but I wont deploy this version either.

**Comment by Heizmann** [comment]
And do you have an idea how we can analyze this problem? What is missing in the crash logs?

**Comment by danieldietsch** [comment]
Run the example, dump the script. z3 crashes in iteration 4: 
<code>
[2017-01-26 22:10:09,925 INFO  L238   tOrderPrioritization]: Conjunction of SSA is unsat
[2017-01-26 22:10:09,928 FATAL L258        ToolchainWalker]: An unrecoverable error occured during an interaction with an SMT solver:
de.uni_freiburg.informatik.ultimate.logic.SMTLIBException: External (z3 -smt2 -in SMTLIB2_COMPLIANT=true -t:12000)Received EOF on stdin. No stderr output.
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Executor.parse(Executor.java:209)
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Executor.parseSuccess(Executor.java:222)
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Scriptor.pop(Scriptor.java:139)
        at de.uni_freiburg.informatik.ultimate.modelcheckerutils.smt.managedscript.ManagedScript.pop(ManagedScript.java:128)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.TraceChecker.endTraceCheck(TraceChecker.java:496)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.TraceChecker.unlockSmtManager(TraceChecker.java:472)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.TraceCheckerSpWp.computeInterpolantsUsingUnsatCore(TraceCheckerSpWp.java:238)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.TraceCheckerSpWp.computeInterpolants(TraceCheckerSpWp.java:172)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.TraceCheckerSpWp.<init>(TraceCheckerSpWp.java:159)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.TraceCheckerConstructor.constructForwardBackward(TraceCheckerConstructor.java:244)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.TraceCheckerConstructor.get(TraceCheckerConstructor.java:189)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.MultiTrackTraceAbstractionRefinementStrategy.getTraceChecker(MultiTrackTraceAbstractionRefinementStrategy.java:208)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.TraceAbstractionRefinementEngine.checkFeasibility(TraceAbstractionRefinementEngine.java:161)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.TraceAbstractionRefinementEngine.executeStrategy(TraceAbstractionRefinementEngine.java:138)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.TraceAbstractionRefinementEngine.<init>(TraceAbstractionRefinementEngine.java:85)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.BasicCegarLoop.isCounterexampleFeasible(BasicCegarLoop.java:287)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.AbstractCegarLoop.iterate(AbstractCegarLoop.java:345)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.iterate(TraceAbstractionStarter.java:276)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.runCegarLoops(TraceAbstractionStarter.java:133)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.<init>(TraceAbstractionStarter.java:103)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionObserver.finish(TraceAbstractionObserver.java:105)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runObserver(PluginConnector.java:168)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runTool(PluginConnector.java:151)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.run(PluginConnector.java:128)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.executePluginConnector(ToolchainWalker.java:225)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.processPlugin(ToolchainWalker.java:219)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walkUnprotected(ToolchainWalker.java:139)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walk(ToolchainWalker.java:101)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainManager$Toolchain.processToolchain(ToolchainManager.java:283)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.DefaultToolchainJob.runToolchainDefault(DefaultToolchainJob.java:221)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.BasicToolchainJob.run(BasicToolchainJob.java:133)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: de.uni_freiburg.informatik.ultimate.logic.SMTLIBException: EOF
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Parser$Action$.CUP$do_action(Parser.java:1369)
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Parser.do_action(Parser.java:582)
        at com.github.jhoenicke.javacup.runtime.LRParser.parse(LRParser.java:419)
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Executor.parse(Executor.java:206)
        ... 31 more

</code>

**Comment by Heizmann** [comment]
Thanks. I was able to reproduce the problem and sent a [bug report](https://github.com/Z3Prover/z3/issues/880).

**Comment by danieldietsch** [comment]
Cool. 

I will close this ticket when we have a new release with a dynamically linked z3 version, but so far I think no further action is required.
