### ISSUE TITLE
Convert SMTLibException to Timeout

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#15]
In some cases, Ultimate dies because the SMTSolver ran into a timeout. Currently, we convert this situation to an error, although it should be a timeout. 

This behavior should be changed, possibly in Executor or Scriptor. 

Example stack trace: 
```
[2016-02-17 13:39:26,265 ERROR L194        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction has thrown an Exception!
de.uni_freiburg.informatik.ultimate.logic.SMTLIBException: line 15920 column 10: canceled
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Parser$Action$.CUP$do_action(Parser.java:1339)
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Parser.do_action(Parser.java:584)
        at java_cup.runtime.LRParser.parse(LRParser.java:419)
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Executor.parse(Executor.java:204)
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Executor.parseCheckSatResult(Executor.java:226)
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Scriptor.checkSat(Scriptor.java:222)
[...]
```

**Comment by danieldietsch** [comment]
Should be fixed (forgot commit message)
