### ISSUE TITLE
Fix "AssertionError: unreachable return" in some scenarios

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#153]
Some SV-COMP examples trigger the following assertion error.
````
java.lang.AssertionError: unreachable return
	at de.uni_freiburg.informatik.ultimate.automata.nestedword.DownStateConsistencyCheck.checkIfEachDownStateIsJustified(DownStateConsistencyCheck.java:147)
	at de.uni_freiburg.informatik.ultimate.automata.nestedword.DownStateConsistencyCheck.consistentForState(DownStateConsistencyCheck.java:125)
	at de.uni_freiburg.informatik.ultimate.automata.nestedword.DownStateConsistencyCheck.consistentForAll(DownStateConsistencyCheck.java:105)
	at de.uni_freiburg.informatik.ultimate.automata.nestedword.DownStateConsistencyCheck.<init>(DownStateConsistencyCheck.java:75)
	at de.uni_freiburg.informatik.ultimate.automata.nestedword.DoubleDeckerAutomatonFilteredStates.<init>(DoubleDeckerAutomatonFilteredStates.java:89)
	at de.uni_freiburg.informatik.ultimate.automata.nestedword.operations.Difference.removeDeadEnds(Difference.java:206)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.BasicCegarLoop.refineWithGivenAutomaton(BasicCegarLoop.java:471)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.BasicCegarLoop.refineAbstraction(BasicCegarLoop.java:393)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.AbstractCegarLoop.iterate(AbstractCegarLoop.java:377)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.iterate(TraceAbstractionStarter.java:280)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.runCegarLoops(TraceAbstractionStarter.java:133)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.<init>(TraceAbstractionStarter.java:103)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionObserver.finish(TraceAbstractionObserver.java:105)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runObserver(PluginConnector.java:168)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runTool(PluginConnector.java:151)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.run(PluginConnector.java:128)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.executePluginConnector(ToolchainWalker.java:232)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.processPlugin(ToolchainWalker.java:226)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walkUnprotected(ToolchainWalker.java:142)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walk(ToolchainWalker.java:104)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainManager$Toolchain.processToolchain(ToolchainManager.java:283)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.DefaultToolchainJob.rerunToolchain(DefaultToolchainJob.java:173)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.BasicToolchainJob.run(BasicToolchainJob.java:131)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
````

Discovered and reproducible with 
S: ``ai/svcomp-Reach-32bit-Taipan_Default_Debug.epf``
T: ``AutomizerCInline.xml``
I: ``examples/svcomp/product-lines/email_spec3_product18_false-unreach-call_true-termination.cil.c``

"Minimal" example (smaller was not possible):
S: ``ai/svcomp-Reach-32bit-Taipan_Default_Debug.epf``
T: ``AutomizerBplInline.xml``
I: ``examples/programs/openBugs/bug-unreachable-return.bpl``

Bug also occurs with basic FPandBP settings.

**Comment by alexandernutz** [comment]
More examples for triggering this AssertionError:
S:`examples/settings/chccomp2018/chcToBoogie_automizer.epf`
T:`examples/toolchains/AutomizerCHC.xml`

in `chc-comp/eldarica-misc/LIA/HOLA/`

`02.c.smt2`
`03.c.smt2`
.. and probably many more in that directory

**Comment by alexandernutz** [comment]
Update:
Cannot reproduce the problem with 03.c.smt2 anymore. Still happens on 02.c.smt2 and 10.c.smt2 (perhaps more).

**Comment by Heizmann** [comment]
I was able to reproduce the problem and to reduce the automaton to around 25 states.

**Comment by schillic** [comment]
If it helps I can also have a look. Can you commit/send the automaton?
