### ISSUE TITLE
QuantifierSequence may run for a very long time, not respecting timeout

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#225]
I have a rather peculiar example where the following callstack hangs for more than 30mins:
```
at ....modelcheckerutils.smt.SmtUtils.filterToVarsThatOccurFreelyInTerm(SmtUtils.java:1487)
at ....modelcheckerutils.smt.linearTerms.QuantifierSequence.<init>(QuantifierSequence.java:69)
```

The example is 
 * Input:gpuverifier/testsuite/OpenCL_simplebinomialoptions2_kernel.bpl 
 * Settings:settings/default/automizer/svcomp-Reach-32bit-Automizer_Bitvector.epf 
 * Toolchain:toolchains/AutomizerBplModSet.xml

**Comment by Heizmann** [comment]
I implemented some improvement.
https://github.com/ultimate-pa/ultimate/commit/f8f4ffc7b1cffa06dca2a2b3bbb4885e46d02a2e
However, this change did not had an impact on the real problem which is the following.

* We reach iteration 35 quite quickly.
* After a few minutes most time is spend in some of my code related to quantifier elimination.
* A few minutes later, the JVM (I am using 1.8.0_144-b01) becomes irresponsive for several minutes. The eclipse debugger is unable to connect and the jstack tool does not respond. During that time the java process takes 200% CPU (I have 8 cores and if we run out of memory java usually takes 800% CPU).
* When the JVM becomes responsive again, it takes 0% CPU and jstack always shows the following stack frame.


> "Worker-1" #26 daemon prio=5 os_prio=0 tid=0x00007f90f0001000 nid=0x6757 runnable [0x00007f916bffc000]
>    java.lang.Thread.State: RUNNABLE
>         at de.uni_freiburg.informatik.ultimate.logic.ComputeFreeVariables$AppTermWorker.walk(ComputeFreeVariables.java:95)
>         at de.uni_freiburg.informatik.ultimate.logic.NonRecursive.run(NonRecursive.java:122)
>         at de.uni_freiburg.informatik.ultimate.logic.NonRecursive.run(NonRecursive.java:113)
>         at de.uni_freiburg.informatik.ultimate.logic.Term.getFreeVars(Term.java:79)
>         at de.uni_freiburg.informatik.ultimate.modelcheckerutils.smt.linearTerms.PrenexNormalForm.pullQuantifiers(PrenexNormalForm.java:113)
>         at de.uni_freiburg.informatik.ultimate.modelcheckerutils.smt.linearTerms.PrenexNormalForm.convertApplicationTerm(PrenexNormalForm.java:75)
>         at de.uni_freiburg.informatik.ultimate.logic.TermTransformer$BuildApplicationTerm.walk(TermTransformer.java:297)
>         at de.uni_freiburg.informatik.ultimate.logic.NonRecursive.run(NonRecursive.java:122)
>         at de.uni_freiburg.informatik.ultimate.logic.NonRecursive.run(NonRecursive.java:113)
>         at de.uni_freiburg.informatik.ultimate.logic.TermTransformer.transform(TermTransformer.java:239)
>         at de.uni_freiburg.informatik.ultimate.modelcheckerutils.smt.PartialQuantifierElimination.tryToEliminate(PartialQuantifierElimination.java:89)

I have no idea, hence I add Jochen to the discussion.
Maybe one should check if the problem is reproducible with another JVM.

**Comment by Heizmann** [comment]
Some idea:
Check if the problem is reproducible with another JVM.

**Comment by Heizmann** [comment]
While reproducing this I was using the following JVM arguments.
-Dosgi.requiredJavaVersion=1.7 -XX:MaxPermSize=256m -Xms256m -Xmx8g

**Comment by danieldietsch** [comment]
With your fix, the example in question now produces a timeout on monteverdi. 
I cannot reproduce the behavior you describe on my machines. Monteverdi is running Java 1.8.0_144-b01.
