### ISSUE TITLE
Non-termination in VpDomain

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#231]
The following example leads to a non-terminating loop in the VpDomain: 
 * Input:svcomp/array-memsafety/subseq-alloca_true-valid-memsafety.i 
 * Settings:settings/ai/eq-bench/svcomp-DerefFreeMemtrack-32bit-Automizer_Camel+AI_EQ.epf 
 * Toolchain:toolchains/AbstractInterpretationC.xm

Stacktrace 
````
"Worker-1" #24 prio=5 os_prio=0 tid=0x00007f4df0001000 nid=0x58e8 runnable [0x00007f4e765fb000]
   java.lang.Thread.State: RUNNABLE
        at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
        at java.util.HashSet.<init>(HashSet.java:119)
        at de.uni_freiburg.informatik.ultimate.util.datastructures.UnionFind.<init>(UnionFind.java:80)
        at de.uni_freiburg.informatik.ultimate.util.datastructures.ThreeValuedEquivalenceRelation.<init>(ThreeValuedEquivalenceRelation.java:61)
        at de.uni_freiburg.informatik.ultimate.util.datastructures.CongruenceClosure.<init>(CongruenceClosure.java:102)
        at de.uni_freiburg.informatik.ultimate.util.datastructures.CongruenceClosure.alignElementsAndFunctions(CongruenceClosure.java:398)
        at de.uni_freiburg.informatik.ultimate.util.datastructures.CongruenceClosure.isStrongerThan(CongruenceClosure.java:456)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.WeakEquivalenceGraph$WeakEquivalenceEdgeLabel.isStrongerThan(WeakEquivalenceGraph.java:929)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.WeakEquivalenceGraph$$Lambda$143/1463994299.test(Unknown Source)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.FloydWarshall.run(FloydWarshall.java:94)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.FloydWarshall.<init>(FloydWarshall.java:69)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.WeakEquivalenceGraph.close(WeakEquivalenceGraph.java:261)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.WeqCongruenceClosure.registerNewElement(WeqCongruenceClosure.java:876)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.WeqCongruenceClosure.registerNewElement(WeqCongruenceClosure.java:1)
        at de.uni_freiburg.informatik.ultimate.util.datastructures.CongruenceClosure.addElement(CongruenceClosure.java:222)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.WeqCongruenceClosure.addElement(WeqCongruenceClosure.java:156)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.WeqCongruenceClosure.removeElement(WeqCongruenceClosure.java:708)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.WeqCongruenceClosure.removeElement(WeqCongruenceClosure.java:686)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.EqConstraint.removeElement(EqConstraint.java:381)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.EqConstraintFactory.projectExistentially(EqConstraintFactory.java:326)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.EqDisjunctiveConstraint.lambda$2(EqDisjunctiveConstraint.java:91)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.EqDisjunctiveConstraint$$Lambda$81/2128533177.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
````

**Comment by danieldietsch** [comment]
Similar issue:
2017-09-28_11-18-13-817 ### 25/100 ### Starting test for 
 * Input:``svcomp/ldv-commit-tester/main4_true-unreach-call_arch-x86-oprofile-oprofile-ko--131_1a--79db8ef-1.c ``
  * Settings:``settings/ai/eq-bench/svcomp-Reach-64bit-Automizer_Camel+AI_EQ.epf ``
  * Toolchain:``toolchains/AbstractInterpretationC.xml``

Stacktrace
````
        at java.util.HashMap.put(HashMap.java:611)
        at de.uni_freiburg.informatik.ultimate.util.datastructures.UnionFind.union(UnionFind.java:193)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.CCManager.filterRedundantCcs(WeakEquivalenceGraph.java:1196)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.WeakEquivalenceGraph$WeakEquivalenceEdgeLabel.union(WeakEquivalenceGraph.java:969)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.WeakEquivalenceGraph$$Lambda$145/2052917615.apply(Unknown Source)
        at de.uni_freiburg.informatik.ultimate.plugins.analysis.abstractinterpretationv2.domain.transformula.vp.states.FloydWarshall.run(FloydWarshall.java:92)
````

**Comment by alexandernutz** [comment]
Did some fixes/reworkings today
 - the first of the above programs terminates normally now
 - the first of the above programs terminates now but with an assertion failure (I'll look into it)
 (I did not choose special settings, hoping that that does not make a difference)

So at the non-termination seems fixed for the above two examples (not 100% because we have nondeterministic behavious, maybe it runs into a loop sometimes only).

Keeping the ticket open for other non-termination problems for now.

**Comment by alexandernutz** [comment]
did not encounter non-termination recently, reopen in case..
