### ISSUE TITLE
IndexOutOfBounds in BuchiAutomizer

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#257]
Use TC ``BuchiAutomizerCInline.xml`` and ``settings/default/automizer/svcomp-Termination-32bit-Automizer_Default.epf`` to trigger the following bug.
````
 java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
 	at java.util.ArrayList.get(ArrayList.java:429)
 	at de.uni_freiburg.informatik.ultimate.modelcheckerutils.smt.arrays.ArrayIndex.get(ArrayIndex.java:90)
 	at de.uni_freiburg.informatik.ultimate.modelcheckerutils.smt.mapelimination.MapEliminator.computeDoubletons(MapEliminator.java:772)
 	at de.uni_freiburg.informatik.ultimate.modelcheckerutils.smt.mapelimination.MapEliminator.<init>(MapEliminator.java:158)
 	at de.uni_freiburg.informatik.ultimate.lassoranker.preprocessors.MapEliminationLassoPreprocessor.process(MapEliminationLassoPreprocessor.java:99)
 	at de.uni_freiburg.informatik.ultimate.lassoranker.variables.LassoBuilder.applyPreprocessor(LassoBuilder.java:154)
 	at de.uni_freiburg.informatik.ultimate.lassoranker.variables.LassoBuilder.preprocess(LassoBuilder.java:262)
 	at de.uni_freiburg.informatik.ultimate.lassoranker.LassoAnalysis.preprocess(LassoAnalysis.java:284)
 	at de.uni_freiburg.informatik.ultimate.lassoranker.LassoAnalysis.<init>(LassoAnalysis.java:233)
 	at de.uni_freiburg.informatik.ultimate.plugins.generator.buchiautomizer.LassoCheck.synthesize(LassoCheck.java:828)
 	at de.uni_freiburg.informatik.ultimate.plugins.generator.buchiautomizer.LassoCheck.access$16(LassoCheck.java:755)
 	at de.uni_freiburg.informatik.ultimate.plugins.generator.buchiautomizer.LassoCheck$LassoCheckResult.checkLassoTermination(LassoCheck.java:508)
 	at de.uni_freiburg.informatik.ultimate.plugins.generator.buchiautomizer.LassoCheck$LassoCheckResult.<init>(LassoCheck.java:416)
 	at de.uni_freiburg.informatik.ultimate.plugins.generator.buchiautomizer.LassoCheck.<init>(LassoCheck.java:300)
 	at de.uni_freiburg.informatik.ultimate.plugins.generator.buchiautomizer.BuchiCegarLoop.iterate(BuchiCegarLoop.java:456)
 	at de.uni_freiburg.informatik.ultimate.plugins.generator.buchiautomizer.BuchiAutomizerObserver.doTerminationAnalysis(BuchiAutomizerObserver.java:150)
 	at de.uni_freiburg.informatik.ultimate.plugins.generator.buchiautomizer.BuchiAutomizerObserver.finish(BuchiAutomizerObserver.java:386)
 	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runObserver(PluginConnector.java:168)
 	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runTool(PluginConnector.java:151)
 	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.run(PluginConnector.java:128)
 	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.executePluginConnector(ToolchainWalker.java:232)
 	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.processPlugin(ToolchainWalker.java:226)
 	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walkUnprotected(ToolchainWalker.java:142)
 	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walk(ToolchainWalker.java:104)
 	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainManager$Toolchain.processToolchain(ToolchainManager.java:324)
 	at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.DefaultToolchainJob.runToolchainDefault(DefaultToolchainJob.java:221)
 	at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.BasicToolchainJob.run(BasicToolchainJob.java:134)
 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
````

[Minimal example](https://github.com/ultimate-pa/ultimate/commit/79787895270bdd12e8de53c4081dccbfa4317733#diff-5e6cda27bca4a42f39668f42f2d97a76) is ``examples/termination/bug-IndexOutOfBounds.c``

Approx. 50 benchmarks are affected.

**Comment by Heizmann** [comment]
Problem: MapElimination cannot deal with arrays whose range sort is an array sort.
However, the MapElimination works whenever all select and store terms fall into our pattern `MultiDimensionalStore` and `MultiDimensionalSelect` class.
Since we use a select-over-store optimization this pattern is not guaranteed any more.

I cannot see a simple solution.
* A workaround: Try to "undo" the select-over-store optimization and bring the term into the form of our multi-dimensional pattern whenever possible. I don't know how often this would be applicable. @alexandernutz @jhoenicke what do you think?
* A rather complex solution: Do the MapElimination in two stages. Stage1: eliminate 2-dimensional arrays. Stage2: eliminate 1-dimensional arrays. (of course it should be implemented an arbitrary number of dimensions but for C programs we have only two)

**Comment by danieldietsch** [comment]
It seems like both map elimination variants are affected by this. Perhaps @franksch94  has an idea how the newer variant could do it on-the-fly? 

If not: why is the second solution rather complex? Seems like applying the map eliminator until nothing changes anymore would be easy to implement.

**Comment by Heizmann** [comment]
I mentioned all arguments why I think it is complex above. If you think it is simple enough then go ahead and implement it. I just won't find time this week.

**Comment by danieldietsch** [comment]
Perhaps I was unclear: Your comment sounds like you favour the first over the second solution, because the second is "rather complex". So it seems that there is additional complexity in the second that is not present in the first, You did not mention anything in that direction in your comment.

**Comment by Heizmann** [comment]
I am in favour for the first solution because I would probably not find enough time to implement the second before SV-COMP deadline.

**Comment by danieldietsch** [comment]
Lets wait for the test results until we close the issue.

**Comment by danieldietsch** [comment]
@franksch94 : your solution stops the problem and brings us roughly 10 more examples. I think we can still improve if we try to "undo" the select-over-store optimization, but for now I would consider this issue closed.
