### ISSUE TITLE
Fix SMTLIBException: Undeclared function symbol

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#277]
With 
  * ``toolchains/AutomizerC.xml``
  * ``settings/default/automizer/svcomp-Reach-64bit-Automizer_Default.epf``

Minimal example is [``examples/programs/regression/c/bug-undeclared-function-symbol.c``](https://github.com/ultimate-pa/ultimate/commit/cfa887e7eb90b66859e24e06a84ee39bbb947ad7)

Stacktrace / log snippet: 
````
[2017-11-21 20:08:54,974 INFO  L371      AbstractCegarLoop]: === Iteration 7 === [ldv_assert_linux_kernel_locking_spinlock__one_thread_double_lockErr0AssertViolation, ldv_assert_linux_kernel_locking_spinlock__one_thread_double_unlockErr0
AssertViolation, ldv_assert_linux_kernel_locking_spinlock__one_thread_locked_at_exitErr0AssertViolation]===
[2017-11-21 20:08:54,974 INFO  L82        PathProgramCache]: Analyzing trace with hash 1603406598, now seen corresponding path program 1 times
[2017-11-21 20:08:54,974 INFO  L208   onRefinementStrategy]: Switched to mode SMTINTERPOL_TREE_INTERPOLANTS
[2017-11-21 20:08:54,974 INFO  L91    tionRefinementEngine]: Using refinement strategy CamelRefinementStrategy
[2017-11-21 20:08:54,976 INFO  L101   rtionOrderModulation]: Keeping assertion order NOT_INCREMENTALLY
[2017-11-21 20:08:55,056 INFO  L136    AnnotateAndAsserter]: Conjunction of SSA is unsat
[2017-11-21 20:08:55,059 WARN  L137   erpolLogProxyWrapper]: Using partial proofs (cut at CNF-level).  Set option :produce-proofs to true to get complete proofs.
[2017-11-21 20:08:55,667 INFO  L134       CoverageAnalysis]: Checked inductivity of 65 backedges. 10 proven. 0 refuted. 0 times theorem prover too weak. 55 trivial. 0 not checked.
[2017-11-21 20:08:55,667 INFO  L372   tionRefinementEngine]: Constructing automaton from 1 perfect and 0 imperfect interpolant sequences.
[2017-11-21 20:08:55,667 INFO  L387   tionRefinementEngine]: Number of different interpolants: perfect sequences [5] imperfect sequences [] total 5
[2017-11-21 20:08:55,668 INFO  L409      AbstractCegarLoop]: Interpolant automaton has 5 states
[2017-11-21 20:08:55,668 INFO  L132   InterpolantAutomaton]: Constructing interpolant automaton starting with 5 interpolants.
[2017-11-21 20:08:55,668 INFO  L133   InterpolantAutomaton]: CoverageRelationStatistics Valid=7, Invalid=13, Unknown=0, NotChecked=0, Total=20
[2017-11-21 20:08:55,668 INFO  L87              Difference]: Start difference. First operand 3748 states and 4506 transitions. Second operand 5 states.
[2017-11-21 20:08:56,393 INFO  L142   InterpolantAutomaton]: Switched to read-only mode: deterministic interpolant automaton has 5 states.
[2017-11-21 20:08:56,394 FATAL L265        ToolchainWalker]: An unrecoverable error occured during an interaction with an SMT solver:
de.uni_freiburg.informatik.ultimate.logic.SMTLIBException: Undeclared function symbol (v_~bitwiseOr_154)
        at de.uni_freiburg.informatik.ultimate.logic.NoopScript.term(NoopScript.java:321)
        at de.uni_freiburg.informatik.ultimate.logic.NoopScript.term(NoopScript.java:296)
        at de.uni_freiburg.informatik.ultimate.modelcheckerutils.smt.SmtUtils.termVariable2constant(SmtUtils.java:708)
        at de.uni_freiburg.informatik.ultimate.modelcheckerutils.hoaretriple.IncrementalHoareTripleChecker.renameAuxVarsToCorrespondingConstants(IncrementalHoareTripleChecker.java:736)
        at de.uni_freiburg.informatik.ultimate.modelcheckerutils.hoaretriple.IncrementalHoareTripleChecker.assertCodeBlock(IncrementalHoareTripleChecker.java:387)
        at de.uni_freiburg.informatik.ultimate.modelcheckerutils.hoaretriple.IncrementalHoareTripleChecker.prepareAssertionStackAndAddTransition(IncrementalHoareTripleChecker.java:177)
        at de.uni_freiburg.informatik.ultimate.modelcheckerutils.hoaretriple.IncrementalHoareTripleChecker.checkReturn(IncrementalHoareTripleChecker.java:141)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.predicates.ProtectiveHoareTripleChecker.checkReturn(ProtectiveHoareTripleChecker.java:80)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.predicates.EfficientHoareTripleChecker.checkReturn(EfficientHoareTripleChecker.java:98)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.predicates.CachingHoareTripleChecker.checkReturn(CachingHoareTripleChecker.java:142)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.interpolantautomata.transitionappender.AbstractInterpolantAutomaton$ReturnSuccessorComputationHelper.computeSuccWithSolver(AbstractInterpolantAutomaton.java:444)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.interpolantautomata.transitionappender.BasicAbstractInterpolantAutomaton.chooseFalseSuccessor2(BasicAbstractInterpolantAutomaton.java:106)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.interpolantautomata.transitionappender.BasicAbstractInterpolantAutomaton.computeSuccs(BasicAbstractInterpolantAutomaton.java:72)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.interpolantautomata.transitionappender.BasicAbstractInterpolantAutomaton.computeSuccs(BasicAbstractInterpolantAutomaton.java:1)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.interpolantautomata.transitionappender.AbstractInterpolantAutomaton.returnSuccessors(AbstractInterpolantAutomaton.java:280)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.interpolantautomata.transitionappender.AbstractInterpolantAutomaton.returnSuccessors(AbstractInterpolantAutomaton.java:1)
        at de.uni_freiburg.informatik.ultimate.automata.nestedword.operations.TotalizeNwa.returnSuccessors(TotalizeNwa.java:308)
        at de.uni_freiburg.informatik.ultimate.automata.nestedword.operations.ComplementDeterministicNwa.returnSuccessors(ComplementDeterministicNwa.java:142)
        at de.uni_freiburg.informatik.ultimate.automata.nestedword.operations.ProductNwa.returnSuccessors(ProductNwa.java:284)
        at de.uni_freiburg.informatik.ultimate.automata.nestedword.operations.ProductNwa.returnSuccessorsGivenHier(ProductNwa.java:308)
        at de.uni_freiburg.informatik.ultimate.automata.nestedword.reachablestates.NestedWordAutomatonReachableStates$ReachableStatesComputation.addReturnsAndSuccessors(NestedWordAutomatonReachableStates.java:1112)
        at de.uni_freiburg.informatik.ultimate.automata.nestedword.reachablestates.NestedWordAutomatonReachableStates$ReachableStatesComputation.<init>(NestedWordAutomatonReachableStates.java:946)
        at de.uni_freiburg.informatik.ultimate.automata.nestedword.reachablestates.NestedWordAutomatonReachableStates.<init>(NestedWordAutomatonReachableStates.java:185)
        at de.uni_freiburg.informatik.ultimate.automata.nestedword.operations.Difference.computeDifference(Difference.java:137)
        at de.uni_freiburg.informatik.ultimate.automata.nestedword.operations.Difference.<init>(Difference.java:90)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.BasicCegarLoop.computeAutomataDifference(BasicCegarLoop.java:548)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.BasicCegarLoop.refineAbstraction(BasicCegarLoop.java:518)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.AbstractCegarLoop.iterateInternal(AbstractCegarLoop.java:420)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.AbstractCegarLoop.iterate(AbstractCegarLoop.java:316)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.iterate(TraceAbstractionStarter.java:292)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.runCegarLoops(TraceAbstractionStarter.java:147)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.<init>(TraceAbstractionStarter.java:111)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionObserver.finish(TraceAbstractionObserver.java:117)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runObserver(PluginConnector.java:168)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runTool(PluginConnector.java:151)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.run(PluginConnector.java:128)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.executePluginConnector(ToolchainWalker.java:232)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.processPlugin(ToolchainWalker.java:226)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walkUnprotected(ToolchainWalker.java:142)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walk(ToolchainWalker.java:104)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainManager$Toolchain.processToolchain(ToolchainManager.java:324)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.DefaultToolchainJob.runToolchainDefault(DefaultToolchainJob.java:221)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.BasicToolchainJob.run(BasicToolchainJob.java:134)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
````

**Comment by maul-esel** [comment]
@danieldietsch The corresponding regression tests succeed (e.g. [here](https://monteverdi.informatik.uni-freiburg.de/ci/job/Ultimate%20Nightly/de.uni_freiburg.informatik.ultimate$de.uni_freiburg.informatik.ultimate.regressiontest/2946/testReport/de.uni_freiburg.informatik.ultimate.regressiontest.generic/RegressionTestSuite/I_programs_regression_c_bug_undeclared_function_symbol_c_S_programs_regression_c_AutomizerC_forwardPredicates_epf_T_programs_regression_c_AutomizerC_xml/)) -- fixed?

**Comment by danieldietsch** [comment]
Looks like it, thanks for checking!
