### ISSUE TITLE
IllegalArgumentException: RValue BoogieType incompatible with its CType

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#309]
During recent changes, the following regression has been introduced:

```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: IllegalArgumentException: The value of the constructed RValue has a BoogieType that is incompatible with its CType.
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: IllegalArgumentException: The value of the constructed RValue has a BoogieType that is incompatible with its CType.: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.checkType(RValue.java:94)
```

* 0.1.23-277cfe1 and 0.1.23-fb1c4d9 are known to be affected
* 0.1.23-97ca168 from last week was not affected 

Settings:
* AutomizerMemDerefMemtrack.xml 
* svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf 

The affected program is large, but the error appears in connection with the following code excerpt when ```bmp_logo_mini_evil``` is accessed later:
```
typedef struct {
 uint8_t width, height;
 const uint8_t *data;
} BITMAP;
extern const BITMAP bmp_logo_mini_evil;
const uint8_t bmp_logo_mini_data[] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,};
const BITMAP bmp_logo_mini_evil = {9, 9, bmp_logo_mini_data};
```

**Comment by invd** [comment]
@alexandernutz: the example file you created does in fact work and also closes the issue for the original program.

**Comment by invd** [comment]
Unfortunately, I have found that other versions of the original program still trigger this exact IllegalArgumentException with todays Ultimate 0.1.23-6f35ba1 and identical settings, so it appears that this bug is not comprehensively fixed.

I will update this ticket with further information and likely an example file at the end of the week.

**Comment by invd** [comment]
#330 is solved, but another regression is blocking the original program verification, as detailed in #331.
I will update this ticket once that issue is solved.

**Comment by invd** [comment]
When using the workaround for #331 and the new Ultimate 0.1.23-809e8b6, the original RValue Boogie Type defect from February is still triggered during the translation:

```
[2018-04-18 11:46:26,755 FATAL L292        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator has thrown an exception:
java.lang.IllegalArgumentException: The value of the constructed RValue has a BoogieType that is incompatible with its CType.
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.checkType(RValue.java:94)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.<init>(RValue.java:78)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.<init>(RValue.java:66)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.ExpressionResult.switchToRValueIfNecessary(ExpressionResult.java:224)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.FunctionHandler.handleReturnStatement(FunctionHandler.java:512)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:1884)
```

**Comment by invd** [comment]
Further testing of this issue is blocked by #359.

**Comment by danieldietsch** [comment]
What is the state of this ticket now that #359 is resolved?

**Comment by invd** [comment]
During some quick runs that I aborted after passing the C translation stage, I have not encountered the IAE exceptions, so this issue appears fixed.
