### ISSUE TITLE
Problem with running Ultimate Automizer / Taipan (Unresolved requirement: Require Bundle...)

### ISSUE THREAD

**Issue by chkl** [ultimate-pa/ultimate#320]
Hi everyone,

first of all congratulations for your success at SV-COMP.  I am currently trying to use Ultimate Automizer but I can't get it to work. I am not sure if this issue tracker is the right place to ask for help. In case it is, here is a description of the problem I have encountered.

1.  I downloaded  & unzipped the latest UTaipan release from your Releases page
2. When I run
`./Ultimate.py --architecture 32bit --file ~/sv-benchmarks/c/array-examples/standard_vector_difference_true-unreach-call_ground.c --spec ~/sv-benchmarks/c/ReachSafety.prp`
I get 
```
Checking for ERROR reachability
Using default analysis
Version 3204b741
Calling Ultimate with: java -Dosgi.configuration.area=/home/klingerc/Downloads/UTaipan-linux/data/config -Xmx12G -Xms1G -jar /home/klingerc/Downloads/UTaipan-linux/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -data /home/klingerc/Downloads/UTaipan-linux/data -tc /home/klingerc/Downloads/UTaipan-linux/config/TaipanReach.xml -i /home/klingerc/thesis/sv-benchmarks/c/array-examples/standard_vector_difference_true-unreach-call_ground.c -s /home/klingerc/Downloads/UTaipan-linux/config/svcomp-Reach-32bit-Taipan_Default.epf --cacsl2boogietranslator.entry.function main --witnessprinter.witness.directory /home/klingerc/Downloads/UTaipan-linux --witnessprinter.witness.filename witness.graphml --witnessprinter.write.witness.besides.input.file false --witnessprinter.graph.data.specification CHECK( init(main()), LTL(G ! call(__VERIFIER_error())) )

 --witnessprinter.graph.data.producer Taipan --witnessprinter.graph.data.architecture 32bit --witnessprinter.graph.data.programhash 89169be74c16a9d11c0b1848e4a2305811d62e33
..
Execution finished with exit code 13
Writing output log to file Ultimate.log
Result:
UNKNOWN

```
Where `Ultimate.log` shows
```
An error has occurred. See the log file
./UTaipan-linux/data/config/1520335883873.log.
```
And that file says
```
!SESSION 2018-03-06 12:31:23.701 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_DK
Framework arguments:  -tc /home/klingerc/Downloads/UTaipan-linux/config/TaipanReach.xml -i /home/klingerc/thesis/sv-benchmarks/c/array-examples/standard_vector_difference_true-unreach-call_ground.c -s /home/klingerc/Downloads/UTaipan-linux/config/svcomp-Reach-32bit-Taipan_Default.epf --cacsl2boogietranslator.entry.function main --witnessprinter.witness.directory /home/klingerc/Downloads/UTaipan-linux --witnessprinter.witness.filename witness.graphml --witnessprinter.write.witness.besides.input.file false --witnessprinter.graph.data.specification CHECK( init(main()), LTL(G ! call(__VERIFIER_error())) )

 --witnessprinter.graph.data.producer Taipan --witnessprinter.graph.data.architecture 32bit --witnessprinter.graph.data.programhash 89169be74c16a9d11c0b1848e4a2305811d62e33
Command-line arguments:  -data /home/klingerc/Downloads/UTaipan-linux/data -tc /home/klingerc/Downloads/UTaipan-linux/config/TaipanReach.xml -i /home/klingerc/thesis/sv-benchmarks/c/array-examples/standard_vector_difference_true-unreach-call_ground.c -s /home/klingerc/Downloads/UTaipan-linux/config/svcomp-Reach-32bit-Taipan_Default.epf --cacsl2boogietranslator.entry.function main --witnessprinter.witness.directory /home/klingerc/Downloads/UTaipan-linux --witnessprinter.witness.filename witness.graphml --witnessprinter.write.witness.besides.input.file false --witnessprinter.graph.data.specification CHECK( init(main()), LTL(G ! call(__VERIFIER_error())) )

 --witnessprinter.graph.data.producer Taipan --witnessprinter.graph.data.architecture 32bit --witnessprinter.graph.data.programhash 89169be74c16a9d11c0b1848e4a2305811d62e33

!ENTRY de.uni_freiburg.informatik.ultimate.boogie.parser 4 0 2018-03-06 12:31:24.283
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: de.uni_freiburg.informatik.ultimate.boogie.parser [7]
  Unresolved requirement: Require-Bundle: de.uni_freiburg.informatik.ultimate.lib.core
    -> Bundle-SymbolicName: de.uni_freiburg.informatik.ultimate.lib.core; bundle-version="0.1.23"
       de.uni_freiburg.informatik.ultimate.lib.core [18]
         Unresolved requirement: Require-Bundle: de.uni_freiburg.informatik.ultimate.lib.ultimatemodel; visibility:="reexport"
...
```

Here is the full log  [1520335883873.log](https://github.com/ultimate-pa/ultimate/files/1784831/1520335883873.log)
 Complaining about a lot of unresolved dependencies.

Does anyone know how to fix this?

**Comment by schillic** [comment]
Not sure if this helps, but Taipan != Automizer.

**Comment by chkl** [comment]
Probably I should have mentioned that I tried Automizer and UTaipan and the errors are the same. The output above is indeed from UTaipan

**Comment by danieldietsch** [comment]
Hi @chkl , yes, this is definitely the right place to ask. On what system do you run Ultimate?

**Comment by chkl** [comment]
I'm running on Archlinux.
```
> uname -a
Linux xps 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
> java -version
java version "1.7.0_171"
OpenJDK Runtime Environment (IcedTea 2.6.13) (Arch Linux build 7.u171_2.6.13-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.171-b02, mixed mode)
```

**Comment by danieldietsch** [comment]
Ah ok, I now also see it in the log: 
``java.version=1.7.0_171``
You need Java 1.8

**Comment by chkl** [comment]
```

**Comment by chkl** [comment]
```
> java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
> ./Ultimate.py --architecture 32bit --file ~/sv-benchmarks/c/array-examples/standard_vector_difference_true-unreach-call_ground.c --spec ~/sv-benchmarks/c/ReachSafety.prp
Checking for ERROR reachability
Using default analysis
Version 3204b741
Calling Ultimate with: java -Dosgi.configuration.area=/home/klingerc/Downloads/UTaipan-linux/data/config -Xmx12G -Xms1G -jar /home/klingerc/Downloads/UTaipan-linux/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -data /home/klingerc/Downloads/UTaipan-linux/data -tc /home/klingerc/Downloads/UTaipan-linux/config/TaipanReach.xml -i /home/klingerc/thesis/sv-benchmarks/c/array-examples/standard_vector_difference_true-unreach-call_ground.c -s /home/klingerc/Downloads/UTaipan-linux/config/svcomp-Reach-32bit-Taipan_Default.epf --cacsl2boogietranslator.entry.function main --witnessprinter.witness.directory /home/klingerc/Downloads/UTaipan-linux --witnessprinter.witness.filename witness.graphml --witnessprinter.write.witness.besides.input.file false --witnessprinter.graph.data.specification CHECK( init(main()), LTL(G ! call(__VERIFIER_error())) )

 --witnessprinter.graph.data.producer Taipan --witnessprinter.graph.data.architecture 32bit --witnessprinter.graph.data.programhash 89169be74c16a9d11c0b1848e4a2305811d62e33
..
Execution finished with exit code 13
Writing output log to file Ultimate.log
Result:
UNKNOWN
> cat Ultimate.log 
An error has occurred. See the log file
/home/klingerc/Downloads/UTaipan-linux/data/config/1520341090380.log.
> cat data/config/1520341090380.log 
!SESSION 2018-03-06 13:58:10.279 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_162
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_DK
Framework arguments:  -tc /home/klingerc/Downloads/UTaipan-linux/config/TaipanReach.xml -i /home/klingerc/thesis/sv-benchmarks/c/array-examples/standard_vector_difference_true-unreach-call_ground.c -s /home/klingerc/Downloads/UTaipan-linux/config/svcomp-Reach-32bit-Taipan_Default.epf --cacsl2boogietranslator.entry.function main --witnessprinter.witness.directory /home/klingerc/Downloads/UTaipan-linux --witnessprinter.witness.filename witness.graphml --witnessprinter.write.witness.besides.input.file false --witnessprinter.graph.data.specification CHECK( init(main()), LTL(G ! call(__VERIFIER_error())) )

 --witnessprinter.graph.data.producer Taipan --witnessprinter.graph.data.architecture 32bit --witnessprinter.graph.data.programhash 89169be74c16a9d11c0b1848e4a2305811d62e33
Command-line arguments:  -data /home/klingerc/Downloads/UTaipan-linux/data -tc /home/klingerc/Downloads/UTaipan-linux/config/TaipanReach.xml -i /home/klingerc/thesis/sv-benchmarks/c/array-examples/standard_vector_difference_true-unreach-call_ground.c -s /home/klingerc/Downloads/UTaipan-linux/config/svcomp-Reach-32bit-Taipan_Default.epf --cacsl2boogietranslator.entry.function main --witnessprinter.witness.directory /home/klingerc/Downloads/UTaipan-linux --witnessprinter.witness.filename witness.graphml --witnessprinter.write.witness.besides.input.file false --witnessprinter.graph.data.specification CHECK( init(main()), LTL(G ! call(__VERIFIER_error())) )

 --witnessprinter.graph.data.producer Taipan --witnessprinter.graph.data.architecture 32bit --witnessprinter.graph.data.programhash 89169be74c16a9d11c0b1848e4a2305811d62e33

!ENTRY org.eclipse.osgi 4 0 2018-03-06 13:58:10.796
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "de.uni_freiburg.informatik.ultimate.core.CoreRCP" could not be found in the registry. The applications available are: org.eclipse.ant.core.antRunner, org.eclipse.cdt.core.GeneratePDOM, org.eclipse.equinox.app.error.
        at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
        at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

**Comment by danieldietsch** [comment]
With the current version, it can happen that Ultimate pollutes its own data and config directories after a start with the wrong java version and then crashes in subsequent starts. 
Could you try to delete the current Ultimate folder and use a fresh one from the .zip?

**Comment by chkl** [comment]
Starting from a freshly unzipped folder fixed it for me. Thank you very much! And sorry for bothering.

**Comment by danieldietsch** [comment]
No problem! I mean, we should probably fix the config-self-destruction ;)

**Comment by Heizmann** [comment]
We should add a new TaskIdentifier for the specification that is checked.

**Comment by Heizmann** [comment]
Sorry, I posted a comment to the wrong issue.
