### ISSUE TITLE
NullPointerException: TypeHandler.visit()

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#335]
Ultimate 0.1.23-f020fd9 does not fail gracefully when run against an example program that has not been preprocessed, and instead crashes with a NPE:
[soundness_fprintf_2.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/soundness_fprintf_2.c)

```
[2018-04-02 18:43:44,398 FATAL L292        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator has thrown an exception:
java.lang.NullPointerException
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.TypeHandler.visit(TypeHandler.java:284)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.PRDispatcher.dispatch(PRDispatcher.java:232)
[...]
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: NullPointerException: null
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: NullPointerException: null: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.TypeHandler.visit(TypeHandler.java:284)

```

For the preprocessed program variant, Ultimate correctly throws a `UnsupportedSyntaxResult` as  expected due to the fprintf calls, see #306:

```
  - UnsupportedSyntaxResult [Line: 863]: Unsupported Syntax
    encountered a call to a var args function, var args are not supported at the moment
```

Toolchain: 
* releaseScripts/default/UAutomizer-linux/config/AutomizerMemDerefMemtrack.xml

Settings tested:
* trunk/examples/settings/default/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf

**Comment by invd** [comment]
The NPE is still present for Ultimate 0.1.23-809e8b6, but exact code lines have changed:

```
  - ExceptionOrErrorResult: NullPointerException: null
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: NullPointerException: null: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.TypeHandler.visit(TypeHandler.java:282)
```

**Comment by invd** [comment]
NPE is still present with today's Ultimate version.

```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: NullPointerException: null
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: NullPointerException: null: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.TypeHandler.visit(TypeHandler.java:282)
```

**Comment by gschievelbein** [comment]
Not reproducible anymore

**Comment by invd** [comment]
I agree with @gschievelbein, running Ultimate 97aecd66c1162e91d286d38715432d609764915b against soundness_fprintf_2.c does in fact no longer lead to an NPE and an **UnsupportedSyntaxResult** is returned, which is expected due to the lack of preprocessing for the stdio.h include: 

```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - UnsupportedSyntaxResult [Line: 6]: Unsupported Syntax
    Undefined type FILE
```
When running Ultimate against the preprocessed version, it correctly detects the var args function:

```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - UnsupportedSyntaxResult [Line: 863]: Unsupported Syntax
    encountered a call to a var args function, var args are not supported at the moment
```
