### ISSUE TITLE
crash during variable update

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#344]
<code>
2018-05-10 12:58:34,614: [INFO]: 127.0.0.1 - - [10/May/2018 12:58:34] "POST /hanfor-wip/api/var/update HTTP/1.1" 200 -
2018-05-10 12:58:39,483: [INFO]: Update Variable `MICRO_STATE_STANDBY`
2018-05-10 12:58:39,486: [INFO]: Change type from `int` to `CONST`.
2018-05-10 12:58:39,486: [INFO]: Change value from `` to `0`.
2018-05-10 12:58:39,486: [INFO]: Store updated variables.
2018-05-10 12:58:39,491: [INFO]: Update derived types by parsing affected formalizations.
2018-05-10 12:58:39,491: [ERROR]: 'MICRO_STATE_STANDBY'
Traceback (most recent call last):
  File "/mnt/crypto-storage/firefox/repo/hanfor-venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/crypto-storage/firefox/repo/hanfor-venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 37, in no_cache
    response = make_response(view(*args, **kwargs))
  File "app.py", line 278, in api
    result = utils.update_variable_in_collection(app, request)
  File "/mnt/crypto-storage/firefox/repo/hanfor-wip/hanfor/utils.py", line 552, in update_variable_in_collection
    for rid in var_collection.var_req_mapping[var_name]:
KeyError: 'MICRO_STATE_STANDBY'
2018-05-10 12:58:39,492: [INFO]: 127.0.0.1 - - [10/May/2018 12:58:39] "POST /hanfor-wip/api/var/update HTTP/1.1" 200 
</code>

**Comment by danieldietsch** [comment]
Ticket in wrong tracker
