### ISSUE TITLE
assertion fails in UnitCollector

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#352]
.. seems like a problem in SMTInterpol's interpolation to me.

chc-comp/sally-chc-benchmarks/approximate_agreement/approx.4.smt2
(perhaps more in that directory)

S: examples/settings/chccomp2018/chcToBoogie_automizer.epf
T: examples/toolchains/AutomizerCHC.xml

java.lang.AssertionError
	at de.uni_freiburg.informatik.ultimate.smtinterpol.proof.UnitCollector.seen(UnitCollector.java:127)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.proof.UnitCollector.run(UnitCollector.java:85)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.proof.UnitCollector.collectUnits(UnitCollector.java:76)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.proof.Transformations.lowerUnits(Transformations.java:99)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.proof.Transformations$AvailableTransformations$2.transform(Transformations.java:56)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.retrieveProof(SMTInterpol.java:1279)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.getProof(SMTInterpol.java:794)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.getInterpolants(SMTInterpol.java:917)
	at de.uni_freiburg.informatik.ultimate.modelcheckerutils.smt.managedscript.ManagedScript.getInterpolants(ManagedScript.java:197)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.NestedInterpolantsBuilder.computeCraigInterpolants(NestedInterpolantsBuilder.java:282)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.NestedInterpolantsBuilder.<init>(NestedInterpolantsBuilder.java:165)

**Comment by danieldietsch** [comment]
Attached the script (use ``-ea`` and remove ``.txt`` from filename) [approx.4_iter2_smtinterpol_mixedla_convert.smt2.txt](https://github.com/ultimate-pa/ultimate/files/2090566/approx.4_iter2_smtinterpol_mixedla_convert.smt2.txt)
