### ISSUE TITLE
NullPointerException: null:

### ISSUE THREAD

**Issue by gschievelbein** [ultimate-pa/ultimate#384]
As of the log from 28-09-2018, there occurs  27 Null Pointer Exceptions at various points of the code.
de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: NullPointerException: null:

**Comment by gschievelbein** [comment]
When trying to cast the return of a function of type void, its expression had a null RValue, causing the NullPointerException. This is fixed. If no more causes of a NullPointerException appears, this issue can be closed.

```
void f()
{
  return;
}

int main()
{
  (void) f();
}
```

**Comment by gschievelbein** [comment]
java.lang.NullPointerException
	at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.TypeHandler.areMatchingTypes(TypeHandler.java:1001)

The exception occurs when trying to get the length of String[] mNames, without checking if it was initialized first.

**Comment by gschievelbein** [comment]
java.lang.NullPointerException
	at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.InitializationHandler.constructIndexToInitInfo(InitializationHandler.java:1111)

Trying to get the lrValue from an InitializerResult that has a null rootExpressionResult.
