### ISSUE TITLE
NPE: CArray.isIncomplete

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#391]
Observed in Ultimate 093a8c091187f74480a9df3bb8c0f996b9a38ead on the _combined_09jan2018_nostrwidth_output_ultimate_emptymain_nolinedirectives.c_ program previously shared with Ultimate devs.

This error is only visible for **svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf** settings. When using **-Automizer_Default.epf**, another error is encountered, as documented in #392. 

```
[2018-10-15 13:30:49,709 FATAL L292        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator has thrown an exception:
java.lang.NullPointerException
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.container.c.CArray.isIncomplete(CArray.java:177)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.handleIASTDeclarator(CHandler.java:2606)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:1878)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.PRDispatcher.dispatch(PRDispatcher.java:143)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.processTUchild(CHandler.java:3314)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:2121)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:539)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.PRDispatcher.dispatch(PRDispatcher.java:134)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.MainTranslator.translate(MainTranslator.java:188)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.MainTranslator.run(MainTranslator.java:117)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.MainTranslator.<init>(MainTranslator.java:95)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator.CACSL2BoogieTranslatorObserver.finish(CACSL2BoogieTranslatorObserver.java:129)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runObserver(PluginConnector.java:168)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runTool(PluginConnector.java:151)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.run(PluginConnector.java:128)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.executePluginConnector(ToolchainWalker.java:232)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.processPlugin(ToolchainWalker.java:226)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walkUnprotected(ToolchainWalker.java:142)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walk(ToolchainWalker.java:104)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainManager$Toolchain.processToolchain(ToolchainManager.java:316)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.DefaultToolchainJob.run(DefaultToolchainJob.java:145)
```
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: NullPointerException: null
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: NullPointerException: null: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.container.c.CArray.isIncomplete(CArray.java:177)
```

**Comment by danieldietsch** [comment]
This should be fixed with https://github.com/ultimate-pa/ultimate/commit/155fbacf47a6d2ac401187314f4342e66790b0c0

**Comment by invd** [comment]
I can confirm that the exception no longer occurs in 209b299ef9535958070033c7e6f7441414579320.

**Comment by danieldietsch** [comment]
Good! Can I close the issue / do you close the issue?
