### ISSUE TITLE
NPE: TypeSizes.extractIntegerValueInteger()

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#392]
Observed in Ultimate 093a8c091187f74480a9df3bb8c0f996b9a38ead on the _combined_09jan2018_nostrwidth_output_ultimate_emptymain_nolinedirectives.c_ program previously shared with Ultimate devs.

This error is only visible for **svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf** settings. When using **-Automizer_Bitvector.epf**, another error is encountered, as documented in issue #391. 

```
[2018-10-15 13:40:58,094 FATAL L292        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator has thrown an exception:
java.lang.NullPointerException                                                                                                                                                                                    
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.TypeSizes.extractIntegerValueInteger(TypeSizes.java:371)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.TypeSizes.extractIntegerValue(TypeSizes.java:338)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.expressiontranslation.IntegerTranslation.constructBinaryBitwiseIntegerExpression(IntegerTranslation.java:189)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.expressiontranslation.ExpressionTranslation.constructBinaryBitwiseExpression(ExpressionTranslation.java:128)                            at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.handleBitshiftOperation(CHandler.java:3726)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:884)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.PRDispatcher.dispatch(PRDispatcher.java:282)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:2171)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.PRDispatcher.dispatch(PRDispatcher.java:303)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:664)
[...]
```

```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: NullPointerException: null
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: NullPointerException: null: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.TypeSizes.extractIntegerValueInteger(TypeSizes.java:371)
```

**Comment by invd** [comment]
I can confirm that the error no longer occurs in Ultimate 209b299ef9535958070033c7e6f7441414579320.

**Comment by danieldietsch** [comment]
Good! Can I close the issue / do you close the issue?
