### ISSUE TITLE
SMTLIBException: Cannot name open terms

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#553]
Version c3a52b3
File `nla-digbench-scaling/freire2_valuebound1.c`
Severity: occurs on 42 of 2310 (https://struebli.informatik.uni-freiburg.de/logs/student-acceleration/20210416-091202-student-acceleration-259539aefe-M/overview)

Stacktrace
```
java.lang.AssertionError: de.uni_freiburg.informatik.ultimate.logic.SMTLIBException: Cannot name open terms
	at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.TraceCheck.<init>(TraceCheck.java:237)
	at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.InterpolatingTraceCheck.<init>(InterpolatingTraceCheck.java:90)
	at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.InterpolatingTraceCheckCraig.<init>(InterpolatingTraceCheckCraig.java:89)
	at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.InterpolatingTraceCheckCraig.computeInterpolantsRecursive(InterpolatingTraceCheckCraig.java:378)
	at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.InterpolatingTraceCheckCraig.computeInterpolants(InterpolatingTraceCheckCraig.java:228)
	at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.InterpolatingTraceCheckCraig.<init>(InterpolatingTraceCheckCraig.java:97)
	at de.uni_freiburg.informatik.ultimate.lib.acceleratedinterpolation.Interpolator.generateInterpolantsCraigNested(Interpolator.java:154)
	at de.uni_freiburg.informatik.ultimate.lib.acceleratedinterpolation.Interpolator.generateInterpolants(Interpolator.java:108)
	at de.uni_freiburg.informatik.ultimate.lib.acceleratedinterpolation.AcceleratedInterpolationCore.acceleratedInterpolationCoreIsCorrect(AcceleratedInterpolationCore.java:219)
	at de.uni_freiburg.informatik.ultimate.lib.acceleratedinterpolation.AcceleratedInterpolation.<init>(AcceleratedInterpolation.java:165)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.IpTcStrategyModulePreferences.construct(IpTcStrategyModulePreferences.java:145)
...
```

Log:
https://struebli.informatik.uni-freiburg.de/logs/student-acceleration/20210416-091202-student-acceleration-259539aefe-M/student-acceleration.2021-04-15_22-53-33.logfiles/Automizer%20AcceleratedInterpolation%20Jordan.freire2_valuebound1.yml.log

**Comment by danieldietsch** [comment]
With ``-ea`` its actually 
```
java.lang.AssertionError: free vars in versioneered term: v_~someBinaryDOUBLEComparisonOperation_11,v_~someBinaryDOUBLEComparisonOperation_12
	at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.NestedSsaBuilder$VariableVersioneer.getVersioneeredTerm(NestedSsaBuilder.java:601)
	at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.NestedSsaBuilder.buildSSA(NestedSsaBuilder.java:225)
	at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.NestedSsaBuilder.<init>(NestedSsaBuilder.java:164)
	at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.TraceCheck.checkTrace(TraceCheck.java:297)
	at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.TraceCheck.<init>(TraceCheck.java:208)
...
```
@Heizmann Can you have a look at this?
