### ISSUE TITLE
Question: Howto use LassoRanker?

### ISSUE THREAD

**Issue by danix800** [ultimate-pa/ultimate#648]
I built Ultimate locally in eclipse RCP and the GUI is running, I tried LassoRanker with default setting but the following exception is thrown saying `LassoRanker can only be applied to models constructed by the RCFGBuilder`, could you give any hints on how to use this Plugin? Do we have any detailed docs on this plugin or any general usage docs? Any info on internals would be much better, thanks!
```
[2023-09-22 13:47:18,803 INFO  L112        PluginConnector]: ------------------------LassoRanker----------------------------
[2023-09-22 13:47:18,804 INFO  L270        PluginConnector]: Initializing LassoRanker...
[2023-09-22 13:47:18,806 INFO  L274        PluginConnector]: LassoRanker initialized
[2023-09-22 13:47:18,808 INFO  L184        PluginConnector]: Executing the observer LassoRankerObserver from plugin LassoRanker for "CDTParser AST 22.09 01:47:05" (1/1) ...
[2023-09-22 13:47:20,473 FATAL L?                        ?]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.analysis.lassoranker has thrown an exception:
java.lang.UnsupportedOperationException: LassoRanker can only be applied to models constructed by the RCFGBuilder
	at de.uni_freiburg.informatik.ultimate.plugins.analysis.lassoranker.LassoRankerObserver.process(LassoRankerObserver.java:66)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.modelwalker.DFSTreeWalker.runObserver(DFSTreeWalker.java:65)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.modelwalker.BaseWalker.runObserver(BaseWalker.java:93)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.modelwalker.BaseWalker.run(BaseWalker.java:86)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runObserver(PluginConnector.java:166)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runTool(PluginConnector.java:155)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.run(PluginConnector.java:127)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.executePluginConnector(ToolchainWalker.java:233)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.processPlugin(ToolchainWalker.java:227)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walkUnprotected(ToolchainWalker.java:144)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walk(ToolchainWalker.java:106)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainManager$Toolchain.processToolchain(ToolchainManager.java:319)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.RerunFreshToolchainJob.run(RerunFreshToolchainJob.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
[2023-09-22 13:47:20,479 INFO  L158              Benchmark]: Toolchain (without parser) took 15101.67ms. Allocated memory is still 40.9MB. Free memory was 12.1MB in the beginning and 9.8MB in the end (delta: 2.3MB). Peak memory consumption was 2.1MB. Max. memory is 4.3GB.
[2023-09-22 13:47:20,481 INFO  L158              Benchmark]: CDTParser took 1.36ms. Allocated memory is still 40.9MB. Free memory is still 8.7MB. There was no memory consumed. Max. memory is 4.3GB.
[2023-09-22 13:47:20,484 INFO  L158              Benchmark]: RCFGBuilder took 13417.03ms. Allocated memory is still 40.9MB. Free memory was 12.0MB in the beginning and 10.6MB in the end (delta: 1.5MB). Peak memory consumption was 2.1MB. Max. memory is 4.3GB.
[2023-09-22 13:47:20,486 INFO  L158              Benchmark]: LassoRanker took 1674.91ms. Allocated memory is still 40.9MB. Free memory was 10.5MB in the beginning and 9.8MB in the end (delta: 631.1kB). There was no memory consumed. Max. memory is 4.3GB.
```

**Comment by danix800** [comment]
I found the way to run it successfully, by choosing toolchain from `trunk/examples/toolchains/LassoRanker.xml` instead of select `LassoRanker` from left pane. Thanks anyway.
